baseURL = 'https://oldrev.github.io/'
languageCode = 'zh-cn'
title = '命叔瞎扯'
copyright = '李维（Li Wei）'
theme = 'diary'
[params]
  description = '制作严肃艺术（不许笑的那种）作品，主要内容是关于禅与电单车维修'
  enableSearch = true
  numberOfTagsShown = 14
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'



[permalinks]
posts = "/:year/:month/:slug/"


[Menus]
  main = [
      {Name = "关于我", URL = "/pages/about"},
      {Name = "博客文章", URL = "/posts"},
      {Name = "GitHub", URL = "https://github.com/oldrev/"},
      {Name = "Twitter/X", URL = "https://x.com/oldrev"}
  ]

[services]
  [services.googleAnalytics]
    id = "G-9DMRBC2QL5"  # Your Google Analytics ID
